### ISSUE TITLE
Create a Github profile

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/.github#8]
So we would get a page like this:
https://github.com/jenkinsci/

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/91831478/149799626-b928388f-b866-4bfe-bc41-98cebc7cb7ce.png">

- [ ] Create a profile with https://github.com/jenkins-infra/.github/new/master?org_profile_readme=1 like https://github.com/jenkinsci/.github/blob/master/profile/README.md
- [ ] add a map of jenkins related orgs

**Comment by lemeurherve** [comment]
Sub issue, add a link to [jenkins-infra](https://github.com/jenkins-infra/helpdesk/issues/new/choose) on https://github.com/jenkinsci/ profile for infra issues.

**Comment by oleg-nenashev** [comment]
+1 from me! Note that for the layout purposes it is better to have a short summary, not a full page https://www.jenkins.io/projects/infrastructure/ . It would be also nice to have quick navigation to the `jenkinsci` GitHub org

**Comment by lemeurherve** [comment]
Yes, that's what I had planned, I [followed its implementation](https://community.jenkins.io/t/proposal-adding-profile-pages-to-github-orgs/578/7) for jenkinsci :)
